In [1]:
#step 1 import library
import pandas as pd

In [2]:
#step 2 import data / read data
admission = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Admission%20Chance.csv')

In [3]:
admission.head(10)

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
5,6,330,115,5,4.5,3.0,9.34,1,0.90
6,7,321,109,3,3.0,4.0,8.20,1,0.75
7,8,308,101,2,3.0,4.0,7.90,0,0.68
8,9,302,102,1,2.0,1.5,8.00,0,0.50
9,10,323,108,3,3.5,3.0,8.60,0,0.45

In [4]:
admission.tail()

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [5]:
admission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No          400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4    SOP               400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.2 KB

In [6]:
admission.describe()

,Serial No,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [7]:
# describe target and features
admission.columns

Index(['Serial No', 'GRE Score', 'TOEFL Score', 'University Rating', ' SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [11]:
#setting target
y=admission['Chance of Admit ']

#setting features
X = admission[['GRE Score', 'TOEFL Score', 'University Rating', ' SOP',
       'LOR ', 'CGPA', 'Research']]

In [18]:
print("Shape of X is : ",X.shape)
print("Shape of y is : ",y.shape)

Shape of X is :  (400, 7)
Shape of y is :  (400,)

In [14]:
# step 4 : train test & split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2529 )

In [19]:
# check shape of train and test sample
print("Shape of X_train is : ",X_train.shape)
print("Shape of X_test is : ",X_test.shape)
print("Shape of y_train is : ",y_train.shape)
print("Shape of y_test is : ",y_test.shape)

Shape of X_train is :  (300, 7)
Shape of X_test is :  (100, 7)
Shape of y_train is :  (300,)
Shape of y_test is :  (100,)

In [22]:
# Step 5 : select model
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [23]:
# Step 6 : train or fit model
model.fit(X_train,y_train)

LinearRegression()

In [24]:
# calculating intercept and coefficient of model
print("Intercept is : ", model.intercept_)
print("Coefficient  is : ", model.coef_)

Intercept is :  -1.250445038169678
Coefficient  is :  [ 0.00178135  0.00333643  0.00448022 -0.00363339  0.01931061  0.11349064
  0.02362743]

In [26]:
#Step 7 : Predict model using predict() function
y_predict = model.predict(X_test)

In [29]:
#Model Accuracy
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error

In [30]:
print("Mean Absolute Error Of Model is : ",mean_absolute_error(y_test, y_predict))

Mean Absolute Error Of Model is :  0.047014230798166995

In [31]:
print("Mean Absolute Percentage Error Of Model is : ",mean_absolute_percentage_error(y_test, y_predict))

Mean Absolute Percentage Error Of Model is :  0.08239957446730994

In [32]:
print("Mean Square Error Of Model is : ",mean_squared_error(y_test, y_predict))

Mean Square Error Of Model is :  0.004433740148085069